### ISSUE TITLE
Place of this Component

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/base-build_server_scripts#1]
I just put this component here that all rock-core dev's can maintain the buildserver-scritps
This might be useful is some new setting are available or some errors on the doc/homepage gen occur. 

I don't know a place for this, but the push-rights needs to be highly limited because this package contains files that are directly and automatic executed on our build servers.

I'm open for discussions.

**Comment by planthaber** [comment]
I think this should ne be in rock-core because it is misleading.

The name "base-build_scripts" suggest that this is the way to build rock-core, but the repo contains scripts for building rock (including the preparation for API upload) on jenkins servers.

The code used to be on gitorious, but I used a non-public clone because of security concerns.
I think this it should stay like this, internal build servers should NEVER use this repo directly without an extra review (but this is another topic).

Though I have no opinion on publishing the scripts (they were public before), but rock-core is not the right place. or at least the repo name should be changed to be NOT misleading.

> This might be useful is some new setting are available or some errors on the doc/homepage gen occur

It is not, because that person would need access to the buildserver itself to trigger an script update and a build

**Comment by doudou** [comment]
> It is not, because that person would need access to the buildserver itself to trigger an script update and a build

It is useful for people to setup _new_ build servers.

I definitely :+1: the inclusion, but another name should be chosen. Why not build_server_scripts (I think that was the actual name)

**Comment by goldhoorn** [comment]
I'm fine with renaming, will do in a few days until someone disagree

**Comment by planthaber** [comment]
> It is useful for people to setup new build servers.

That's true, then we should also move the howto from the rock.opendfki page to the wiki or readme.md here and re-organize the folders of the repo to make the scripts purpose more understandable

**Comment by goldhoorn** [comment]
I do the rename and close this issue
